version: 2

build:
  os: "ubuntu-lts-latest"
  tools:
    python: "mambaforge-latest"
  commands:
    - conda run -n readthedocs make -C docs doxygen

conda:
  environment: docs/environment.yaml

python:
  install:
    - method: pip
      path: .

sphinx:
  configuration: docs/conf.py
