version: 2

build:
  os: "ubuntu-lts-latest"
  tools:
    python: "mambaforge-latest"
#  apt_packages:
#    - doxygen
#    - cmake
#    - ninja-build
  commands:
    - make -C docs doxygen

conda:
  environment_file: docs/environment.yaml

python:
  install:
    - method: pip
      path: .

sphinx:
  configuration: docs/conf.py
