version: 2

build:
  os: "ubuntu-lts-latest"
  tools:
    python: "miniconda-latest"
  apt_packages:
      - doxygen
      - cmake
      - ninja
  commands:
    - mkdir -p docs/_build_doxygen
    - cd docs/_build_doxygen && cmake ../.. -DBUILD_DOCS=ON -DBUILD_PYTHON=ON -DBUILD_TESTS=OFF -DUSE_CUDA=OFF && cmake --build . --target doxygen-docs && cmake --build .

conda:
  environment: docs/environment.yaml

sphinx:
  configuration: docs/conf.py
