version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
    - doxygen
    - cmake
    - ninja-build
  commands:
    - cmake -S . -B build -DBUILD_DOCS=ON -DBUILD_PYTHON=ON -DBUILD_TESTS=OFF -DUSE_CUDA=OFF
    - cmake --build build --target doxygen-docs parallelproj_backend

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/conf.py
