version: 2

build:
  os: ubuntu-24.04
  tools:
    python: miniconda-latest

  apt_packages:
    - doxygen
    - cmake
    - ninja-build

  jobs:
    # Make sure git history + tags are available so `git describe` works reliably
    post_checkout:
      - git fetch --unshallow || true
      - git fetch --tags --force || true

    pre_build:
      - mkdir -p docs/_build_doxygen
      - cd docs/_build_doxygen && cmake ../.. -DBUILD_DOCS=ON -DBUILD_PYTHON=ON -DBUILD_TESTS=OFF -DUSE_CUDA=OFF
      - cd docs/_build_doxygen && cmake --build . --target doxygen-docs
      - cd docs/_build_doxygen && cmake --build .

conda:
  environment: docs/environment.yaml

sphinx:
  configuration: docs/conf.py
