name: libparallelproj_cuda13_build_only

channels:
  - conda-forge

dependencies:
  - cxx-compiler            # [linux]
  - cuda-compiler =13
  - cmake >=3.31
  - ninja
  - nanobind
  - python >=3.12,<4
  - numpy
  - array-api-compat
  - array-api-strict
  - pytest
