name: readthedocs
channels:
  - conda-forge
dependencies:
  - cxx-compiler
  - cmake>=3.18
  - ninja
  - doxygen
  - graphviz
  - python>=3.12
  - pip
  - sphinx>=8,<9 # build does not work with sphinx 9 yet, probably breath 5 needed
  - breathe>=4,<5
  - sphinx-gallery
  - sphinx-design
  - furo
  - nanobind
  - sphinxcontrib-bibtex
  - matplotlib
  - array-api-compat
  - pytorch=2=cpu*

