name: readthedocs
channels:
  - conda-forge
dependencies:
  - cxx-compiler
  - cmake
  - ninja
  - doxygen
  - graphviz
  - python
  - pip
  - sphinx>=7,<9
  - breathe
  - sphinx-gallery
  - sphinx-design
  - furo
  - nanobind
  - sphinxcontrib-bibtex
  - matplotlib
  - array-api-compat
  - pytorch

