name: CUDA Build

on:
  push:
    branches: [main]
    paths:
      - 'src/*_worker.h'
      - 'src/*.cu'
      - 'python/bindings.cpp'
      - 'CMakeLists.txt'
      - '.github/workflows/build_cuda.yml'
  pull_request:
    paths:
      - 'src/*_worker.h'
      - 'src/*.cu'
      - 'python/bindings.cpp'
      - 'CMakeLists.txt'
      - '.github/workflows/build_cuda.yml'

jobs:
  cuda-build:
    runs-on: ubuntu-latest

    env:
      BUILD_DIR: build

    strategy:
      matrix:
        cuda-version: ['12.4.0', '13.1.0']
      fail-fast: true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install CUDA Toolkit
        id: cuda-toolkit
        uses: Jimver/cuda-toolkit@v0.2.30
        with:
          cuda: ${{ matrix.cuda-version }}
          method: 'local'
          log-file-suffix: '${{ matrix.cuda-version }}.txt'

      #- name: Install Build Tools
      #  run: sudo apt-get update && sudo apt-get install -y cmake ninja-build

      - name: Check CUDA Setup
        run: |
          echo "CUDA Path: ${{ steps.cuda-toolkit.outputs.CUDA_PATH }}"
          which nvcc
          nvcc --version
          g++ --version

      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml
          micromamba-version: latest
          init-shell: bash
          post-cleanup: all

      - name: Show python version
        shell: bash -l {0}
        run: python -V

      - name: Configure and Build with CMake
        shell: bash -l {0}
        run: |
          micromamba activate libparallelproj
          cmake --preset cuda -B $BUILD_DIR \
            -DCUDAToolkit_ROOT=${{ steps.cuda-toolkit.outputs.CUDA_PATH }} \
            -DCMAKE_CUDA_COMPILER=${{ steps.cuda-toolkit.outputs.CUDA_PATH }}/bin/nvcc
          cmake --build $BUILD_DIR

      - name: Run python tests (should be skipped if no physical GPU is available)
        shell: bash -l {0}
        env:
          PYTHON: ${{ env.BUILD_DIR }}
        run: |
          micromamba activate libparallelproj
          pytest -v tests

      - name: Install
        shell: bash -el {0}
        run: |
          cmake --install $BUILD_DIR

      - name: Uninstall
        shell: bash -el {0}
        run: |
          cmake --build $BUILD_DIR --target uninstall

      - name: Clean up CUDA Toolkit
        shell: bash -l {0}
        if: always()
        run: |
          echo "Cleaning up CUDA install..."
          sudo rm -rf /usr/local/cuda*
          sudo rm -rf ~/.cuda-toolkit
          sudo rm -rf ~/cuda_installer*
